sudo: false
compiler: clang
env:
  - CC=clang CXX=clang++ npm_config_clang=1
addons:
  addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

branches:
  only:
    - master
    - /^ena-.*$/

before_install:
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
- source $HOME/.bashrc
- nvm install 0.12
- npm install
- npm run compile

install:
- node server/prepare.js
- node server/build.js

after_success:
- node server/deploy.js

os:
- linux
- osx
