language: node_js
node_js: 0.12
sudo: false
compiler: clang
env:
  - CC=clang CXX=clang++ npm_config_clang=1
addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

branches:
  only:
    - master
    - /^ena-.*$/

before_install:
- npm install
- npm run compile

install:
- node ci/prepare.js
- node ci/build.js

after_success:
- node ci/deploy.js

os:
- linux
- osx
